# Generated by Django 4.1.2 on 2022-12-05 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_post', models.CharField(max_length=1000)),
                ('date_post', models.DateTimeField(auto_now_add=True)),
                ('likes_post', models.IntegerField(default='0')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='network.newpost')),
                ('users_like', models.ManyToManyField(blank=True, related_name='users_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_follow', models.ManyToManyField(blank=True, related_name='followed_follow', to=settings.AUTH_USER_MODEL)),
                ('followers_follow', models.ManyToManyField(blank=True, related_name='followers_follow', to=settings.AUTH_USER_MODEL)),
                ('user_follow', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_follow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
