# Generated by Django 4.1.2 on 2022-12-07 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_follow_followed_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user_follow',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
