# Generated by Django 4.1.2 on 2022-12-11 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_follow_followed_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed_follow',
            field=models.ManyToManyField(blank=True, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followers_follow',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like_like', to='network.newpost'),
        ),
        migrations.AlterField(
            model_name='like',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='users_like_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
