# Generated by Django 4.1.2 on 2022-12-11 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_follow_followers_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed_follow',
        ),
        migrations.AddField(
            model_name='follow',
            name='followed_follow',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='who_followed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
