# Generated by Django 4.1.2 on 2022-12-12 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_follow_followed_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed_follow',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='who_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
